@startuml NumbersSquared

' Style options
skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor PaleGreen
    ArrowColor SeaGreen
    BorderColor SpringGreen
}
skinparam interface {
    BackgroundColor LightSkyBlue
    ArrowColor SteelBlue
    BorderColor DeepSkyBlue
}
hide empty members

class NumbersSquared implements Iterator {
  - start: int
  - end: int
  - current: int
  + __construct(start: int, end: int)
  + rewind(): void
  + valid(): bool
  + next(): void
  + key(): int
  + current(): int
}

interface Iterator {
  + rewind(): void
  + valid(): bool
  + next(): void
  + key(): mixed
  + current(): mixed
}

@enduml 